/**
 * SWIFT Message Routes for SwiftNexus Enterprise
 * Industry Standard SWIFT MT Message Generation and Processing
 */

import express from 'express';
import rateLimit from 'express-rate-limit';
import SwiftMessageGenerator from '../utils/swiftMessageGeneratorEnhanced.js';
import { authenticateToken, requireRole } from '../middleware/auth.js';
import logger from '../config/logger.js';

const router = express.Router();
const swiftGenerator = new SwiftMessageGenerator();

// Rate limiting for SWIFT operations
const swiftLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 50, // Limit each IP to 50 SWIFT requests per windowMs
  message: {
    error: 'Too many SWIFT requests, please try again later',
    retryAfter: '15 minutes'
  }
});

// Apply rate limiting to all SWIFT routes
router.use(swiftLimiter);

/**
 * Generate SWIFT MT103 (Customer Credit Transfer)
 */
router.post('/generate/mt103', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const {
      senderBIC,
      receiverBIC,
      transactionReference,
      relatedReference,
      date,
      currency,
      amount,
      orderingCustomer,
      beneficiaryCustomer,
      beneficiaryBank,
      paymentDetails,
      charges,
      senderToReceiverInfo
    } = req.body;

    // Validate required fields
    const required = ['senderBIC', 'receiverBIC', 'transactionReference', 'currency', 'amount', 'orderingCustomer', 'beneficiaryCustomer'];
    const missing = required.filter(field => !req.body[field]);
    
    if (missing.length > 0) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields',
        missing: missing
      });
    }

    // Validate BIC codes (8 or 11 characters)
    const bicRegex = /^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$/;
    if (!bicRegex.test(senderBIC) || !bicRegex.test(receiverBIC)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid BIC code format'
      });
    }

    // Validate currency (3 letter ISO code)
    const currencyRegex = /^[A-Z]{3}$/;
    if (!currencyRegex.test(currency)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid currency code format'
      });
    }

    // Validate amount (positive number)
    const amountNum = parseFloat(amount);
    if (isNaN(amountNum) || amountNum <= 0) {
      return res.status(400).json({
        success: false,
        error: 'Invalid amount'
      });
    }

    const swiftMessage = swiftGenerator.generateMT103({
      senderBIC: senderBIC.toUpperCase(),
      receiverBIC: receiverBIC.toUpperCase(),
      transactionReference,
      relatedReference,
      date: date || new Date().toISOString().split('T')[0].replace(/-/g, ''),
      currency: currency.toUpperCase(),
      amount: amountNum.toFixed(2).padStart(15, '0'),
      orderingCustomer,
      beneficiaryCustomer,
      beneficiaryBank,
      paymentDetails,
      charges: charges || 'SHA',
      senderToReceiverInfo
    });

    // Validate generated message
    const validation = swiftGenerator.validateSwiftMessage(swiftMessage);
    if (!validation.isValid) {
      return res.status(500).json({
        success: false,
        error: 'Generated SWIFT message validation failed',
        validationErrors: validation.errors
      });
    }

    logger.info(`SWIFT MT103 generated by user ${req.user.id}: ${transactionReference}`);

    res.json({
      success: true,
      data: {
        messageType: 'MT103',
        swiftMessage,
        transactionReference,
        validation
      }
    });

  } catch (error) {
    logger.error('Error generating SWIFT MT103:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate SWIFT MT103 message'
    });
  }
});

/**
 * Generate SWIFT MT199 (Free Format Message)
 */
router.post('/generate/mt199', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const {
      senderBIC,
      receiverBIC,
      transactionReference,
      messageContent,
      priority = 'N'
    } = req.body;

    // Validate required fields
    const required = ['senderBIC', 'receiverBIC', 'transactionReference', 'messageContent'];
    const missing = required.filter(field => !req.body[field]);
    
    if (missing.length > 0) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields',
        missing: missing
      });
    }

    // Validate BIC codes
    const bicRegex = /^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$/;
    if (!bicRegex.test(senderBIC) || !bicRegex.test(receiverBIC)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid BIC code format'
      });
    }

    const swiftMessage = swiftGenerator.generateMT199({
      senderBIC: senderBIC.toUpperCase(),
      receiverBIC: receiverBIC.toUpperCase(),
      transactionReference,
      messageContent,
      priority
    });

    // Validate generated message
    const validation = swiftGenerator.validateSwiftMessage(swiftMessage);
    if (!validation.isValid) {
      return res.status(500).json({
        success: false,
        error: 'Generated SWIFT message validation failed',
        validationErrors: validation.errors
      });
    }

    logger.info(`SWIFT MT199 generated by user ${req.user.id}: ${transactionReference}`);

    res.json({
      success: true,
      data: {
        messageType: 'MT199',
        swiftMessage,
        transactionReference,
        validation
      }
    });

  } catch (error) {
    logger.error('Error generating SWIFT MT199:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate SWIFT MT199 message'
    });
  }
});

/**
 * Generate SWIFT MT940 (Customer Statement)
 */
router.post('/generate/mt940', authenticateToken, requireRole(['admin']), async (req, res) => {
  try {
    const {
      senderBIC,
      receiverBIC,
      accountNumber,
      statementNumber,
      openingBalance,
      closingBalance,
      transactions
    } = req.body;

    // Validate required fields
    const required = ['senderBIC', 'receiverBIC', 'accountNumber', 'statementNumber', 'openingBalance', 'closingBalance'];
    const missing = required.filter(field => !req.body[field]);
    
    if (missing.length > 0) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields',
        missing: missing
      });
    }

    // Validate BIC codes
    const bicRegex = /^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$/;
    if (!bicRegex.test(senderBIC) || !bicRegex.test(receiverBIC)) {
      return res.status(400).json({
        success: false,
        error: 'Invalid BIC code format'
      });
    }

    const swiftMessage = swiftGenerator.generateMT940({
      senderBIC: senderBIC.toUpperCase(),
      receiverBIC: receiverBIC.toUpperCase(),
      accountNumber,
      statementNumber,
      openingBalance,
      closingBalance,
      transactions: transactions || []
    });

    // Validate generated message
    const validation = swiftGenerator.validateSwiftMessage(swiftMessage);
    if (!validation.isValid) {
      return res.status(500).json({
        success: false,
        error: 'Generated SWIFT message validation failed',
        validationErrors: validation.errors
      });
    }

    logger.info(`SWIFT MT940 generated by admin ${req.user.id}: ${accountNumber}`);

    res.json({
      success: true,
      data: {
        messageType: 'MT940',
        swiftMessage,
        accountNumber,
        statementNumber,
        validation
      }
    });

  } catch (error) {
    logger.error('Error generating SWIFT MT940:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate SWIFT MT940 message'
    });
  }
});

/**
 * Validate SWIFT message
 */
router.post('/validate', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const { swiftMessage } = req.body;

    if (!swiftMessage) {
      return res.status(400).json({
        success: false,
        error: 'SWIFT message is required'
      });
    }

    const validation = swiftGenerator.validateSwiftMessage(swiftMessage);

    res.json({
      success: true,
      data: {
        validation,
        parsedMessage: swiftGenerator.parseSwiftMessage(swiftMessage)
      }
    });

  } catch (error) {
    logger.error('Error validating SWIFT message:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to validate SWIFT message'
    });
  }
});

/**
 * Parse SWIFT message
 */
router.post('/parse', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const { swiftMessage } = req.body;

    if (!swiftMessage) {
      return res.status(400).json({
        success: false,
        error: 'SWIFT message is required'
      });
    }

    const parsedMessage = swiftGenerator.parseSwiftMessage(swiftMessage);

    res.json({
      success: true,
      data: {
        parsedMessage
      }
    });

  } catch (error) {
    logger.error('Error parsing SWIFT message:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to parse SWIFT message'
    });
  }
});

/**
 * Generate UETR (Unique End-to-End Transaction Reference)
 */
router.get('/generateuetr', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const uetr = swiftGenerator.generateUETR();

    res.json({
      success: true,
      data: {
        uetr
      }
    });

  } catch (error) {
    logger.error('Error generating UETR:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate UETR'
    });
  }
});

/**
 * Get supported SWIFT message types
 */
router.get('/messagetypes', authenticateToken, async (req, res) => {
  try {
    res.json({
      success: true,
      data: {
        messageTypes: swiftGenerator.messageTypes,
        priorityCodes: swiftGenerator.priorityCodes
      }
    });

  } catch (error) {
    logger.error('Error getting SWIFT message types:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get SWIFT message types'
    });
  }
});

export default router;
