/**
 * Complete SWIFT Message Routes for SwiftNexus Enterprise
 * All MT Message Types (0-9 Categories) + MX Messages
 */

import express from 'express';
import rateLimit from 'express-rate-limit';
import SwiftMessageGenerator from '../utils/swiftMessageGeneratorEnhanced.js';
import { authenticateToken, requireRole } from '../middleware/auth.js';
import logger from '../config/logger.js';

const router = express.Router();
const swiftGenerator = new SwiftMessageGenerator();

// Rate limiting for SWIFT operations
const swiftLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 50, // Limit each IP to 50 SWIFT requests per windowMs
  message: {
    error: 'Too many SWIFT requests, please try again later',
    retryAfter: '15 minutes'
  }
});

// Apply rate limiting to all SWIFT routes
router.use(swiftLimiter);

/**
 * Generate any SWIFT MT message by type
 */
router.post('/generate/:messageType', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const { messageType } = req.params;
    const messageData = req.body;

    // Validate message type exists
    const allMessageTypes = swiftGenerator.getAllMessageTypes();
    if (!allMessageTypes.mt[messageType]) {
      return res.status(400).json({
        success: false,
        error: `Invalid message type: ${messageType}`,
        availableTypes: Object.keys(allMessageTypes.mt)
      });
    }

    // Validate required fields based on message type
    const requiredFields = getRequiredFields(messageType);
    const missing = requiredFields.filter(field => !messageData[field]);
    
    if (missing.length > 0) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields',
        missing: missing,
        required: requiredFields
      });
    }

    // Generate message based on type
    let swiftMessage;
    switch (messageType) {
      case 'MT103':
        swiftMessage = swiftGenerator.generateMT103(messageData);
        break;
      case 'MT199':
        swiftMessage = swiftGenerator.generateMT199(messageData);
        break;
      case 'MT940':
        swiftMessage = swiftGenerator.generateMT940(messageData);
        break;
      case 'MT202':
        swiftMessage = swiftGenerator.generateMT202(messageData);
        break;
      case 'MT300':
        swiftMessage = swiftGenerator.generateMT300(messageData);
        break;
      case 'MT320':
        swiftMessage = swiftGenerator.generateMT320(messageData);
        break;
      case 'MT540':
        swiftMessage = swiftGenerator.generateMT540(messageData);
        break;
      case 'MT541':
        swiftMessage = swiftGenerator.generateMT541(messageData);
        break;
      case 'MT542':
        swiftMessage = swiftGenerator.generateMT542(messageData);
        break;
      case 'MT700':
        swiftMessage = swiftGenerator.generateMT700(messageData);
        break;
      case 'MT710':
        swiftMessage = swiftGenerator.generateMT710(messageData);
        break;
      case 'MT799':
        swiftMessage = swiftGenerator.generateMT799(messageData);
        break;
      case 'MT910':
        swiftMessage = swiftGenerator.generateMT910(messageData);
        break;
      case 'MT950':
        swiftMessage = swiftGenerator.generateMT950(messageData);
        break;
      default:
        // Generate generic message for other types
        swiftMessage = generateGenericMessage(messageType, messageData);
        break;
    }

    // Validate generated message
    const validation = swiftGenerator.validateSwiftMessage(swiftMessage);
    if (!validation.isValid) {
      return res.status(500).json({
        success: false,
        error: 'Generated SWIFT message validation failed',
        validationErrors: validation.errors
      });
    }

    logger.info(`SWIFT ${messageType} generated by user ${req.user.id}`);

    res.json({
      success: true,
      data: {
        messageType,
        messageDescription: allMessageTypes.mt[messageType],
        swiftMessage,
        validation,
        category: getCategoryFromMessageType(messageType)
      }
    });

  } catch (error) {
    logger.error(`Error generating SWIFT ${req.params.messageType}:`, error);
    res.status(500).json({
      success: false,
      error: `Failed to generate SWIFT ${req.params.messageType} message`
    });
  }
});

/**
 * Generate MX Message (ISO 20022)
 */
router.post('/generate/mx/:messageType', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const { messageType } = req.params;
    const messageData = req.body;

    // Validate MX message type exists
    const allMessageTypes = swiftGenerator.getAllMessageTypes();
    if (!allMessageTypes.mx[messageType]) {
      return res.status(400).json({
        success: false,
        error: `Invalid MX message type: ${messageType}`,
        availableTypes: Object.keys(allMessageTypes.mx)
      });
    }

    let mxMessage;
    switch (messageType) {
      case 'pacs.008':
        mxMessage = swiftGenerator.generatePacs008(messageData);
        break;
      case 'camt.052':
        mxMessage = swiftGenerator.generateCamt052(messageData);
        break;
      default:
        mxMessage = swiftGenerator.generateMXMessage(messageType, messageData);
        break;
    }

    logger.info(`SWIFT MX ${messageType} generated by user ${req.user.id}`);

    res.json({
      success: true,
      data: {
        messageType,
        messageDescription: allMessageTypes.mx[messageType],
        mxMessage,
        format: 'ISO 20022 XML'
      }
    });

  } catch (error) {
    logger.error(`Error generating SWIFT MX ${req.params.messageType}:`, error);
    res.status(500).json({
      success: false,
      error: `Failed to generate SWIFT MX ${req.params.messageType} message`
    });
  }
});

/**
 * Convert MT to MX message
 */
router.post('/convert/mt-to-mx', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const { mtMessage, messageType } = req.body;

    if (!mtMessage || !messageType) {
      return res.status(400).json({
        success: false,
        error: 'MT message and message type are required'
      });
    }

    const mxMessage = swiftGenerator.convertMTtoMX(mtMessage, messageType);

    logger.info(`SWIFT ${messageType} converted to MX by user ${req.user.id}`);

    res.json({
      success: true,
      data: {
        originalMessageType: messageType,
        convertedToMX: mxMessage,
        mtMessage,
        conversionType: 'ISO 20022 Migration'
      }
    });

  } catch (error) {
    logger.error('Error converting MT to MX:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to convert MT to MX message'
    });
  }
});

/**
 * Get all supported message types
 */
router.get('/messagetypes', authenticateToken, async (req, res) => {
  try {
    const allMessageTypes = swiftGenerator.getAllMessageTypes();
    const categories = swiftGenerator.getMessageTypesByCategory();

    res.json({
      success: true,
      data: {
        mt: allMessageTypes.mt,
        mx: allMessageTypes.mx,
        categories,
        priorityCodes: swiftGenerator.priorityCodes,
        totalMTTypes: Object.keys(allMessageTypes.mt).length,
        totalMXTypes: Object.keys(allMessageTypes.mx).length
      }
    });

  } catch (error) {
    logger.error('Error getting SWIFT message types:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get SWIFT message types'
    });
  }
});

/**
 * Get message types by category
 */
router.get('/categories', authenticateToken, async (req, res) => {
  try {
    const categories = swiftGenerator.getMessageTypesByCategory();

    res.json({
      success: true,
      data: {
        categories,
        categoryDescriptions: {
          '0': 'System Messages',
          '1': 'Customer Payments & Cheques',
          '2': 'Financial Institution Transfers',
          '3': 'Treasury Markets',
          '4': 'Collections & Cash Letters',
          '5': 'Securities Markets',
          '6': 'Treasury Markets - Precious Metals',
          '7': 'Documentary Credits & Guarantees',
          '8': 'Travellers Cheques',
          '9': 'Cash Management & Customer Status'
        }
      }
    });

  } catch (error) {
    logger.error('Error getting SWIFT categories:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to get SWIFT categories'
    });
  }
});

/**
 * Get message type details
 */
router.get('/details/:messageType', authenticateToken, async (req, res) => {
  try {
    const { messageType } = req.params;
    const allMessageTypes = swiftGenerator.getAllMessageTypes();

    const mtType = allMessageTypes.mt[messageType];
    const mxType = allMessageTypes.mx[messageType];

    if (!mtType && !mxType) {
      return res.status(404).json({
        success: false,
        error: `Message type ${messageType} not found`
      });
    }

    res.json({
      success: true,
      data: {
        messageType,
        description: mtType || mxType,
        type: mtType ? 'MT' : 'MX',
        category: mtType ? getCategoryFromMessageType(messageType) : 'MX',
        requiredFields: getRequiredFields(messageType),
        sampleFields: getSampleFields(messageType)
      }
    });

  } catch (error) {
    logger.error(`Error getting SWIFT message details for ${req.params.messageType}:`, error);
    res.status(500).json({
      success: false,
      error: 'Failed to get SWIFT message details'
    });
  }
});

/**
 * Validate SWIFT message
 */
router.post('/validate', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const { swiftMessage } = req.body;

    if (!swiftMessage) {
      return res.status(400).json({
        success: false,
        error: 'SWIFT message is required'
      });
    }

    const validation = swiftGenerator.validateSwiftMessage(swiftMessage);
    const parsedMessage = swiftGenerator.parseSwiftMessage(swiftMessage);

    res.json({
      success: true,
      data: {
        validation,
        parsedMessage
      }
    });

  } catch (error) {
    logger.error('Error validating SWIFT message:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to validate SWIFT message'
    });
  }
});

/**
 * Parse SWIFT message
 */
router.post('/parse', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const { swiftMessage } = req.body;

    if (!swiftMessage) {
      return res.status(400).json({
        success: false,
        error: 'SWIFT message is required'
      });
    }

    const parsedMessage = swiftGenerator.parseSwiftMessage(swiftMessage);

    res.json({
      success: true,
      data: {
        parsedMessage
      }
    });

  } catch (error) {
    logger.error('Error parsing SWIFT message:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to parse SWIFT message'
    });
  }
});

/**
 * Generate UETR (Unique End-to-End Transaction Reference)
 */
router.get('/generateuetr', authenticateToken, requireRole(['admin', 'user']), async (req, res) => {
  try {
    const uetr = swiftGenerator.generateUETR();

    res.json({
      success: true,
      data: {
        uetr
      }
    });

  } catch (error) {
    logger.error('Error generating UETR:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to generate UETR'
    });
  }
});

// Helper functions
function getRequiredFields(messageType) {
  const fieldMap = {
    'MT103': ['senderBIC', 'receiverBIC', 'transactionReference', 'currency', 'amount', 'orderingCustomer', 'beneficiaryCustomer'],
    'MT199': ['senderBIC', 'receiverBIC', 'transactionReference', 'messageContent'],
    'MT940': ['senderBIC', 'receiverBIC', 'accountNumber', 'statementNumber', 'openingBalance', 'closingBalance'],
    'MT202': ['senderBIC', 'receiverBIC', 'transactionReference', 'currency', 'amount'],
    'MT300': ['senderBIC', 'receiverBIC', 'transactionReference', 'currency', 'amount', 'exchangeRate'],
    'MT320': ['senderBIC', 'receiverBIC', 'transactionReference', 'currency', 'amount', 'interestRate'],
    'MT540': ['senderBIC', 'receiverBIC', 'transactionReference', 'securityIdentification', 'quantity'],
    'MT541': ['senderBIC', 'receiverBIC', 'transactionReference', 'securityIdentification', 'quantity'],
    'MT542': ['senderBIC', 'receiverBIC', 'transactionReference', 'securityIdentification', 'quantity', 'settlementAmount'],
    'MT700': ['senderBIC', 'receiverBIC', 'transactionReference', 'documentaryCreditNumber', 'applicant', 'beneficiary'],
    'MT710': ['senderBIC', 'receiverBIC', 'transactionReference', 'documentaryCreditNumber', 'issuingBank'],
    'MT799': ['senderBIC', 'receiverBIC', 'transactionReference', 'messageContent'],
    'MT910': ['senderBIC', 'receiverBIC', 'transactionReference', 'accountNumber', 'amount'],
    'MT950': ['senderBIC', 'receiverBIC', 'transactionReference', 'accountNumber', 'statementData']
  };

  return fieldMap[messageType] || ['senderBIC', 'receiverBIC', 'transactionReference'];
}

function getSampleFields(messageType) {
  const sampleMap = {
    'MT103': {
      senderBIC: 'SCBLDEFXXXX',
      receiverBIC: 'SBININBBXXX',
      transactionReference: 'TXN20240129001',
      currency: 'USD',
      amount: '1000.00',
      orderingCustomer: 'John Doe',
      beneficiaryCustomer: 'Jane Smith',
      paymentDetails: 'Payment for services'
    },
    'MT199': {
      senderBIC: 'SCBLDEFXXXX',
      receiverBIC: 'SBININBBXXX',
      transactionReference: 'MSG20240129001',
      messageContent: 'Please confirm receipt of funds'
    },
    'MT940': {
      senderBIC: 'SCBLDEFXXXX',
      receiverBIC: 'SBININBBXXX',
      accountNumber: '1234567890',
      statementNumber: 'STMT001',
      openingBalance: 'CUSD10000.00',
      closingBalance: 'CUSD9500.00'
    }
  };

  return sampleMap[messageType] || {};
}

function getCategoryFromMessageType(messageType) {
  if (messageType.startsWith('MT')) {
    return messageType.substring(2, 3); // Get the third digit
  }
  return 'MX';
}

function generateGenericMessage(messageType, messageData) {
  // Generate a generic SWIFT message for unsupported types
  const { senderBIC, receiverBIC, transactionReference, ...otherFields } = messageData;
  
  const basicHeader = swiftGenerator.generateBasicHeader(senderBIC);
  const applicationHeader = swiftGenerator.generateApplicationHeader(messageType, receiverBIC);
  const userHeader = swiftGenerator.generateUserHeader();
  
  const textFields = {
    '20': transactionReference,
    ...otherFields
  };
  
  const textBlock = swiftGenerator.generateTextBlock(textFields);
  const trailer = swiftGenerator.generateTrailer();

  return `${basicHeader}\n${applicationHeader}\n${userHeader}\n${textBlock}\n${trailer}`;
}

export default router;
